{{/*
AUTOGENERATED FILE - DO NOT EDIT.
Generated by scripts/generate_env_tpls.py from charts/agentarea/config.yaml
*/}}

{{- define "agentarea.application.configVars" -}}
{{- end }}

{{- define "agentarea.application.envs" }}
- name: SECRET_MANAGER_ENCRYPTION_KEY
  valueFrom:
    secretKeyRef:
      name: "{{ .Values.global.secrets.application }}"
      key: encryption-key
{{- end }}

{{- define "agentarea.application.secrets.envs" }}
- name: SECRET_MANAGER_ENCRYPTION_KEY
  valueFrom:
    secretKeyRef:
      name: "{{ .Values.global.secrets.application }}"
      key: encryption-key
{{- end }}
