{{/*
AUTOGENERATED FILE - DO NOT EDIT.
Generated by scripts/generate_env_tpls.py from charts/agentarea/config.yaml
*/}}

{{- define "agentarea.frontend.configVars" -}}
PORT: "3000"
NODE_ENV: "production"
API_URL: "http://{{ include "agentarea.fullname" . }}-backend:8000"
ORY_ADMIN_URL: "http://{{ include "agentarea.fullname" . }}-kratos-admin:4434"
ORY_SDK_URL: "http://{{ include "agentarea.fullname" . }}-kratos-public:4433"
NEXT_PUBLIC_ORY_SDK_URL: "http://{{ include "agentarea.fullname" . }}-kratos-public:4433"
METRICS_ENABLED: "{{ .Values.global.monitoring.prometheus.enabled }}"
HEALTH_CHECK_ENABLED: "{{ .Values.global.monitoring.health.enabled }}"
{{- end }}

{{- define "agentarea.frontend.envs" }}
- name: PORT
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env
      key: PORT
- name: NODE_ENV
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env
      key: NODE_ENV
- name: API_URL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env
      key: API_URL
- name: ORY_ADMIN_URL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env
      key: ORY_ADMIN_URL
- name: ORY_SDK_URL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env
      key: ORY_SDK_URL
- name: NEXT_PUBLIC_ORY_SDK_URL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env
      key: NEXT_PUBLIC_ORY_SDK_URL
- name: METRICS_ENABLED
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env
      key: METRICS_ENABLED
- name: HEALTH_CHECK_ENABLED
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env
      key: HEALTH_CHECK_ENABLED
{{- end }}
