{{/*
AUTOGENERATED FILE - DO NOT EDIT.
Generated by scripts/generate_env_tpls.py from charts/agentarea/config.yaml
*/}}

{{- define "agentarea.mcpManager.configVars" -}}
LOG_LEVEL: "INFO"
CORE_API_URL: "http://{{ include "agentarea.fullname" . }}-backend:8000"
TRAEFIK_NETWORK: "podman"
SERVER_HOST: "0.0.0.0"
SERVER_PORT: "80"
MCP_PROXY_HOST: "http://{{ include "agentarea.fullname" . }}-mcp-manager"
{{- end }}

{{- define "agentarea.mcpManager.envs" }}
- name: LOG_LEVEL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: LOG_LEVEL
- name: CORE_API_URL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: CORE_API_URL
- name: TRAEFIK_NETWORK
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: TRAEFIK_NETWORK
- name: SERVER_HOST
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: SERVER_HOST
- name: SERVER_PORT
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: SERVER_PORT
- name: MCP_PROXY_HOST
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: MCP_PROXY_HOST
{{- end }}
