{{/*
AUTOGENERATED FILE - DO NOT EDIT.
Generated by scripts/generate_env_tpls.py from charts/agentarea/config.yaml
*/}}

{{- define "agentarea.redis.configVars" -}}
REDIS_HOST: "{{ .Release.Name }}-redis-master"
REDIS_PORT: "{{ .Values.global.redis.port }}"
{{- end }}

{{- define "agentarea.redis.envs" }}
- name: REDIS_HOST
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env
      key: REDIS_HOST
- name: REDIS_PORT
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env
      key: REDIS_PORT
- name: REDIS_PASSWORD
  valueFrom:
    secretKeyRef:
      name: "{{ .Values.global.secrets.redis }}"
      key: redis-password
- name: REDIS_URL
  value: redis://:$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)
{{- end }}

{{- define "agentarea.redis.secrets.envs" }}
- name: REDIS_PASSWORD
  valueFrom:
    secretKeyRef:
      name: "{{ .Values.global.secrets.redis }}"
      key: redis-password
{{- end }}
