{{/*
AUTOGENERATED FILE - DO NOT EDIT.
Generated by scripts/generate_env_tpls.py from charts/agentarea/config.yaml
*/}}

{{- define "agentarea.storage.configVars" -}}
AWS_REGION: "{{ .Values.global.storage.region }}"
S3_BUCKET_NAME: "{{ .Values.global.storage.bucket }}"
AWS_ENDPOINT_URL: "http://{{ .Release.Name }}-minio:9000"
{{- end }}

{{- define "agentarea.storage.envs" }}
- name: AWS_REGION
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env
      key: AWS_REGION
- name: S3_BUCKET_NAME
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env
      key: S3_BUCKET_NAME
- name: AWS_ENDPOINT_URL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env
      key: AWS_ENDPOINT_URL
- name: AWS_ACCESS_KEY_ID
  valueFrom:
    secretKeyRef:
      name: "{{ .Values.global.secrets.minio }}"
      key: root-user
- name: AWS_SECRET_ACCESS_KEY
  valueFrom:
    secretKeyRef:
      name: "{{ .Values.global.secrets.minio }}"
      key: root-password
{{- end }}

{{- define "agentarea.storage.secrets.envs" }}
- name: AWS_ACCESS_KEY_ID
  valueFrom:
    secretKeyRef:
      name: "{{ .Values.global.secrets.minio }}"
      key: root-user
- name: AWS_SECRET_ACCESS_KEY
  valueFrom:
    secretKeyRef:
      name: "{{ .Values.global.secrets.minio }}"
      key: root-password
{{- end }}
