{{/*
AUTOGENERATED FILE - DO NOT EDIT.
Generated by scripts/generate_env_tpls.py from charts/agentarea/config.yaml
*/}}

{{- define "agentarea.temporalUi.configVars" -}}
TEMPORAL_ADDRESS: "{{ include "agentarea.fullname" . }}-temporal:7233"
TEMPORAL_CORS_ORIGINS: "http://localhost:3000"
{{- end }}

{{- define "agentarea.temporalUi.envs" }}
- name: TEMPORAL_ADDRESS
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env
      key: TEMPORAL_ADDRESS
- name: TEMPORAL_CORS_ORIGINS
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env
      key: TEMPORAL_CORS_ORIGINS
{{- end }}
