{{/*
AUTOGENERATED FILE - DO NOT EDIT.
Generated by scripts/generate_env_tpls.py from charts/agentarea/config.yaml
*/}}

{{- define "agentarea.temporalServer.configVars" -}}
DB: "postgres12"
DB_PORT: "5432"
POSTGRES_SEEDS: "{{ .Release.Name }}-postgresql"
DBNAME: "{{ .Values.global.database.name }}"
BIND_ON_IP: "0.0.0.0"
{{- end }}

{{- define "agentarea.temporalServer.envs" }}
- name: DB
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env
      key: DB
- name: DB_PORT
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env
      key: DB_PORT
- name: POSTGRES_SEEDS
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env
      key: POSTGRES_SEEDS
- name: DBNAME
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env
      key: DBNAME
- name: BIND_ON_IP
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env
      key: BIND_ON_IP
- name: POSTGRES_USER
  valueFrom:
    secretKeyRef:
      name: "{{ .Values.global.secrets.postgresql }}"
      key: username
- name: POSTGRES_PWD
  valueFrom:
    secretKeyRef:
      name: "{{ .Values.global.secrets.postgresql }}"
      key: password
{{- end }}

{{- define "agentarea.temporalServer.secrets.envs" }}
- name: POSTGRES_USER
  valueFrom:
    secretKeyRef:
      name: "{{ .Values.global.secrets.postgresql }}"
      key: username
- name: POSTGRES_PWD
  valueFrom:
    secretKeyRef:
      name: "{{ .Values.global.secrets.postgresql }}"
      key: password
{{- end }}
