{{/*
AUTOGENERATED FILE - DO NOT EDIT.
Generated by scripts/generate_env_tpls.py from charts/agentarea/config.yaml
*/}}

{{- define "agentarea.temporal.configVars" -}}
WORKFLOW__TEMPORAL_SERVER_URL: "{{ include "agentarea.fullname" . }}-temporal:{{ .Values.global.temporal.port }}"
WORKFLOW__TEMPORAL_NAMESPACE: "{{ .Values.global.temporal.namespace }}"
WORKFLOW__TEMPORAL_TASK_QUEUE: "{{ .Values.global.temporal.taskQueue }}"
{{- end }}

{{- define "agentarea.temporal.envs" }}
- name: WORKFLOW__TEMPORAL_SERVER_URL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env
      key: WORKFLOW__TEMPORAL_SERVER_URL
- name: WORKFLOW__TEMPORAL_NAMESPACE
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env
      key: WORKFLOW__TEMPORAL_NAMESPACE
- name: WORKFLOW__TEMPORAL_TASK_QUEUE
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env
      key: WORKFLOW__TEMPORAL_TASK_QUEUE
{{- end }}
