{{/*
AUTOGENERATED FILE - DO NOT EDIT.
Generated by scripts/generate_env_tpls.py from charts/agentarea/config.yaml
*/}}

{{- define "agentarea.worker.configVars" -}}
WORKFLOW__USE_WORKFLOW_EXECUTION: "true"
WORKFLOW__WORKFLOW_ENGINE: "temporal"
WORKFLOW__TEMPORAL_MAX_CONCURRENT_ACTIVITIES: "10"
WORKFLOW__TEMPORAL_MAX_CONCURRENT_WORKFLOWS: "5"
TASK__ENABLE_DYNAMIC_ACTIVITY_DISCOVERY: "true"
DEBUG: "false"
ENVIRONMENT: "production"
{{- end }}

{{- define "agentarea.worker.envs" }}
- name: WORKFLOW__USE_WORKFLOW_EXECUTION
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-worker
      key: WORKFLOW__USE_WORKFLOW_EXECUTION
- name: WORKFLOW__WORKFLOW_ENGINE
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-worker
      key: WORKFLOW__WORKFLOW_ENGINE
- name: WORKFLOW__TEMPORAL_MAX_CONCURRENT_ACTIVITIES
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-worker
      key: WORKFLOW__TEMPORAL_MAX_CONCURRENT_ACTIVITIES
- name: WORKFLOW__TEMPORAL_MAX_CONCURRENT_WORKFLOWS
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-worker
      key: WORKFLOW__TEMPORAL_MAX_CONCURRENT_WORKFLOWS
- name: TASK__ENABLE_DYNAMIC_ACTIVITY_DISCOVERY
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-worker
      key: TASK__ENABLE_DYNAMIC_ACTIVITY_DISCOVERY
- name: DEBUG
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-worker
      key: DEBUG
- name: ENVIRONMENT
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-worker
      key: ENVIRONMENT
{{- end }}
